version: "3.3"

services:
  bankjobs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: bankjobs
    restart: always
    env_file: .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - NUXT_HOST=${NUXT_HOST}
      - NUXT_PORT=${NUXT_PORT}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - MONGO_RETRIES=${MONGO_RETRIES}
      - SECRET=${SECRET}
      - MAIL_SERVICE=${MAIL_SERVICE}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_SECURE=${MAIL_SECURE}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - MAIL_SENDER=${MAIL_SENDER}
      - MAIL_RECEIVERS=${MAIL_RECEIVERS}
    depends_on:
      - bankjobs-db
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      bankjobs-network:
        aliases: 
          - bankjobs.localhost

    command: ./db.sh bankjobs-db:27017 -- npm start

  bankjobs-db:
    image: mongo:4.1.8-xenial
    container_name: bankjobs-db
    restart: unless-stopped
    ports:
      - "30001:27017"
    volumes:
      - dbdata:/data/db
    networks:
      bankjobs-network:
        aliases:
          - bankjobs-db.localhost

networks:
  bankjobs-network:
    driver: bridge

volumes:
  dbdata:
    external: true
  node_modules:

